version: '2.1'
services:
  srs:
    image: spanda/srs
    container_name: srs
    volumes:
    - ./log:/opt/objs/tmp
    - ./demo.conf:/opt/objs/conf/http.hls.conf
    network_mode: host
    restart: always